{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "026d5f0d-3891-4874-85cf-73e13d2e8de3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter your name: Otuya\n",
      "Enter your weight in pounds: 150\n",
      "Enter height in inches: 69\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "22.14870825456837\n",
      "Otuya, you are normal\n"
     ]
    }
   ],
   "source": [
    "Name = input( 'Enter your name:')\n",
    "weight = int(input('Enter your weight in pounds:'))\n",
    "height = int(input('Enter height in inches:'))\n",
    "BMI = (weight * 703)/(height *height)\n",
    "print(BMI)\n",
    "if BMI > 0:\n",
    "    if BMI < 18.5:\n",
    "        print (Name +', you are under weight')\n",
    "    if BMI < 24.9:\n",
    "        print (Name +', you are normal')\n",
    "    else:\n",
    "        print(Name +', eat more fruits')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "633f14c7-2215-419e-931d-7817f12552a3",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d0cfc3e2-d884-4072-bea4-028e77533591",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d5e12dcf-7bae-4509-9ad5-c6ad75883ca9",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "62499353-9184-4de3-bda4-c3e871f4a7ab",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a3d5aa0c-dda7-4b87-9ed1-3941d0348106",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dc9310f4-58e6-4ac1-b10e-882d5a01fa07",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2d7196ea-a9a5-45db-87c2-063c330e8daa",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b51de876-ea15-49d7-8a5d-109ab2903626",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "14acd473-c2c9-4969-88fa-b51c1b8e4667",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6756c3c6-9f2f-4121-9f11-24a5b6515450",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d581f5aa-532c-42b1-a5f6-1892aa7fede3",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "41dd7210-6675-450f-a7de-31146acac4fe",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cfbb92a4-a065-44e2-a91d-673ee2544cee",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "74c39196-be80-48a1-83ea-9398c51b0cae",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "585b3a97-1094-405e-bb8e-acf38b9242ef",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cde4a446-f44e-486b-809c-bdb4fc3a11dd",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eb84e81d-15b1-48b2-b985-2921bbe5ce8c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "373545b3-f622-4e67-b1af-62f5ed52fe65",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3cf50813-db07-44f7-858a-35f32e16a82a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
